export const RUTAS_FIREBASE = {
  PATH_FIREBASE_MOTOCICLETAS_EN_VENTA: 'motocicletas',
  PATH_FIREBASE_TABLES_TIENDA: 'tienda',

  PATH_FIREBASE_TABLES_USUARIOS: 'users',
  PATH_FIREBASE_TABLES_CLIENTES: 'clientes_v1',
};
